version : '3'
services:
  db:
    image: postgres:14.6
    build:
      context: .
      dockerfile: Dockerfile_postgres
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=students3
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - datadocker:/var/lib/postgresql/data
    ports:
      - "29429:5432"
    networks:
      k6:
        aliases:
          - db_host
  app:
      build: .
      environment:
        DB_HOST: db_host
        DB_PORT: 5432
        DB_NAME: students3
        DB_USER: postgres
        DB_PASSWORD: root
      ports:
          - "3000:3000"
      depends_on:
        - db
      networks:
          k6:
            aliases:
              - backend_host
volumes:
  data: {}
  deployments: {}
  datadocker:

networks:
  k6:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
    ipam:
      driver: default

